name: Update README

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "PR #${{ github.event.pull_request.number }} by ${{ github.event.pull_request.user.login }} was merged on $(date + '%Y-%m-%d')." >> README.md

      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'Github Action'
          git commit -am "Update README with PR info"
          git push
